-- Careers.lua
-- Defines career path templates with rank-gated advance tables.
-- Each career has multiple ranks; each rank has an XP threshold and a table of purchasable advances.
-- Loaded by Engine::init() via sol2.

careers = {
    {
        name = "Rogue Trader",
        description = "A scion of a powerful dynasty, granted a Warrant of Trade by the God-Emperor himself. You command your vessel and crew through force of personality, cunning negotiation, and sheer audacity.",
        hp = 38.0,
        defense = 2.0,
        power = 4.0,
        invSize = 26,
        startingEquipment = { "Laspistol", "Combat Knife", "Flak Armor" },
        ranks = {
            {
                rankNumber = 1,
                rankTitle = "Rogue Trader",
                xpThreshold = 0,
                startingSkills = { "Command", "Commerce" },
                startingTalents = { "Pistol Weapon Training (Universal)" },
                advances = {
                    { type = "characteristic", name = "WS",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "BS",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "Fel", cost = 100, amount = 5 },
                    { type = "characteristic", name = "WP",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "Int", cost = 250, amount = 5 },
                    { type = "skill",          name = "Command",   cost = 100 },
                    { type = "skill",          name = "Commerce",  cost = 100 },
                    { type = "skill",          name = "Charm",     cost = 100 },
                    { type = "talent",         name = "Air of Authority", cost = 200 },
                    { type = "talent",         name = "Exceptional Leader", cost = 200 },
                },
            },
            {
                rankNumber = 2,
                rankTitle = "Master Trader",
                xpThreshold = 500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "Fel", cost = 250, amount = 5 },
                    { type = "characteristic", name = "WP",  cost = 250, amount = 5 },
                    { type = "characteristic", name = "Int", cost = 250, amount = 5 },
                    { type = "skill",          name = "Barter",    cost = 200 },
                    { type = "skill",          name = "Evaluate",  cost = 200 },
                    { type = "talent",         name = "Iron Discipline", cost = 300 },
                    { type = "talent",         name = "Master Orator",   cost = 300 },
                },
            },
            {
                rankNumber = 3,
                rankTitle = "Warrant Holder",
                xpThreshold = 1500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "Fel", cost = 500, amount = 5 },
                    { type = "characteristic", name = "WS",  cost = 500, amount = 5 },
                    { type = "characteristic", name = "BS",  cost = 500, amount = 5 },
                    { type = "skill",          name = "Command",   cost = 300 },
                    { type = "skill",          name = "Intimidate", cost = 300 },
                    { type = "talent",         name = "Into the Jaws of Hell", cost = 500 },
                },
            },
        },
    },
    {
        name = "Arch-Militant",
        description = "A warrior without peer, trained in every form of combat known to the Imperium. You are the first into the breach and the last to leave, a living weapon wielded by your Rogue Trader.",
        hp = 42.0,
        defense = 3.0,
        power = 6.0,
        invSize = 22,
        startingEquipment = { "Chainsword", "Autogun", "Flak Armor", "Carapace Helm" },
        ranks = {
            {
                rankNumber = 1,
                rankTitle = "Arch-Militant",
                xpThreshold = 0,
                startingSkills = { "Dodge", "Awareness" },
                startingTalents = { "Basic Weapon Training (Universal)" },
                advances = {
                    { type = "characteristic", name = "WS",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "BS",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "S",   cost = 100, amount = 5 },
                    { type = "characteristic", name = "T",   cost = 250, amount = 5 },
                    { type = "characteristic", name = "Ag",  cost = 100, amount = 5 },
                    { type = "skill",          name = "Dodge",     cost = 100 },
                    { type = "skill",          name = "Awareness", cost = 100 },
                    { type = "skill",          name = "Intimidate", cost = 100 },
                    { type = "talent",         name = "Crushing Blow",   cost = 200 },
                    { type = "talent",         name = "Swift Attack",    cost = 200 },
                },
            },
            {
                rankNumber = 2,
                rankTitle = "Warrior Prime",
                xpThreshold = 500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "WS",  cost = 250, amount = 5 },
                    { type = "characteristic", name = "BS",  cost = 250, amount = 5 },
                    { type = "characteristic", name = "S",   cost = 250, amount = 5 },
                    { type = "characteristic", name = "T",   cost = 250, amount = 5 },
                    { type = "skill",          name = "Parry",     cost = 200 },
                    { type = "skill",          name = "Scrutiny",  cost = 200 },
                    { type = "talent",         name = "Lightning Attack", cost = 300 },
                    { type = "talent",         name = "Combat Master",    cost = 300 },
                },
            },
            {
                rankNumber = 3,
                rankTitle = "Battlemaster",
                xpThreshold = 1500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "WS",  cost = 500, amount = 5 },
                    { type = "characteristic", name = "S",   cost = 500, amount = 5 },
                    { type = "characteristic", name = "T",   cost = 500, amount = 5 },
                    { type = "skill",          name = "Dodge",     cost = 300 },
                    { type = "skill",          name = "Command",   cost = 300 },
                    { type = "talent",         name = "Wall of Steel",   cost = 500 },
                    { type = "talent",         name = "Step Aside",      cost = 500 },
                },
            },
        },
    },
    {
        name = "Void-Master",
        description = "A pilot and navigator of exceptional skill, equally at home in the cockpit of a gun-cutter or at the helm of a voidship. Your reflexes and spatial awareness are unmatched among the crew.",
        hp = 36.0,
        defense = 2.0,
        power = 3.0,
        invSize = 24,
        startingEquipment = { "Laspistol", "Combat Knife", "Flak Armor" },
        ranks = {
            {
                rankNumber = 1,
                rankTitle = "Void-Master",
                xpThreshold = 0,
                startingSkills = { "Pilot (Spacecraft)", "Navigation (Stellar)" },
                startingTalents = { "Pistol Weapon Training (Universal)" },
                advances = {
                    { type = "characteristic", name = "BS",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "Ag",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "Per", cost = 100, amount = 5 },
                    { type = "characteristic", name = "Int", cost = 250, amount = 5 },
                    { type = "skill",          name = "Pilot (Spacecraft)",    cost = 100 },
                    { type = "skill",          name = "Navigation (Stellar)",  cost = 100 },
                    { type = "talent",         name = "Crack Shot",            cost = 200 },
                    { type = "talent",         name = "Lightning Reflexes",    cost = 200 },
                },
            },
            {
                rankNumber = 2,
                rankTitle = "Helmsman",
                xpThreshold = 500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "BS",  cost = 250, amount = 5 },
                    { type = "characteristic", name = "Ag",  cost = 250, amount = 5 },
                    { type = "characteristic", name = "Per", cost = 250, amount = 5 },
                    { type = "skill",          name = "Dodge",      cost = 200 },
                    { type = "skill",          name = "Awareness",  cost = 200 },
                    { type = "talent",         name = "Sharpshooter",  cost = 300 },
                    { type = "talent",         name = "Hard Target",   cost = 300 },
                },
            },
            {
                rankNumber = 3,
                rankTitle = "Fleet Officer",
                xpThreshold = 1500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "BS",  cost = 500, amount = 5 },
                    { type = "characteristic", name = "Int", cost = 500, amount = 5 },
                    { type = "skill",          name = "Command",    cost = 300 },
                    { type = "skill",          name = "Scrutiny",   cost = 300 },
                    { type = "talent",         name = "Master Pilot",    cost = 500 },
                    { type = "talent",         name = "Nerves of Steel", cost = 500 },
                },
            },
        },
    },
    {
        name = "Explorator",
        description = "A Tech-Priest of the Adeptus Mechanicus, driven by an insatiable hunger for lost archeotech and forbidden knowledge. Your mechadendrites and augmetics make you as much machine as man.",
        hp = 40.0,
        defense = 4.0,
        power = 4.0,
        invSize = 20,
        startingEquipment = { "Power Sword", "Flak Armor" },
        ranks = {
            {
                rankNumber = 1,
                rankTitle = "Explorator",
                xpThreshold = 0,
                startingSkills = { "Tech-Use", "Logic" },
                startingTalents = { "Mechadendrite Use (Utility)" },
                advances = {
                    { type = "characteristic", name = "Int", cost = 100, amount = 5 },
                    { type = "characteristic", name = "WP",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "T",   cost = 250, amount = 5 },
                    { type = "characteristic", name = "S",   cost = 250, amount = 5 },
                    { type = "skill",          name = "Tech-Use",  cost = 100 },
                    { type = "skill",          name = "Logic",     cost = 100 },
                    { type = "skill",          name = "Medicae",   cost = 100 },
                    { type = "talent",         name = "Binary Chatter",      cost = 200 },
                    { type = "talent",         name = "Electrical Succour",  cost = 200 },
                },
            },
            {
                rankNumber = 2,
                rankTitle = "Magos Errant",
                xpThreshold = 500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "Int", cost = 250, amount = 5 },
                    { type = "characteristic", name = "WP",  cost = 250, amount = 5 },
                    { type = "characteristic", name = "T",   cost = 250, amount = 5 },
                    { type = "skill",          name = "Chem-Use",                    cost = 200 },
                    { type = "skill",          name = "Forbidden Lore (Archeotech)", cost = 200 },
                    { type = "talent",         name = "Luminen Charge", cost = 300 },
                    { type = "talent",         name = "Ferric Lure",   cost = 300 },
                },
            },
            {
                rankNumber = 3,
                rankTitle = "Arch-Magos",
                xpThreshold = 1500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "Int", cost = 500, amount = 5 },
                    { type = "characteristic", name = "T",   cost = 500, amount = 5 },
                    { type = "characteristic", name = "WP",  cost = 500, amount = 5 },
                    { type = "skill",          name = "Tech-Use",  cost = 300 },
                    { type = "skill",          name = "Security",  cost = 300 },
                    { type = "talent",         name = "Master Enginseer",    cost = 500 },
                    { type = "talent",         name = "Rite of Pure Thought", cost = 500 },
                },
            },
        },
    },
    {
        name = "Missionary",
        description = "A firebrand preacher of the Imperial Creed, spreading the Emperor's word through inspiration and righteous violence in equal measure. Your faith is your shield, and your fury is your sword.",
        hp = 38.0,
        defense = 2.0,
        power = 4.0,
        invSize = 24,
        startingEquipment = { "Chainsword", "Flak Armor" },
        ranks = {
            {
                rankNumber = 1,
                rankTitle = "Missionary",
                xpThreshold = 0,
                startingSkills = { "Command", "Intimidate" },
                startingTalents = { "Melee Weapon Training (Primitive)" },
                advances = {
                    { type = "characteristic", name = "WP",  cost = 100, amount = 5 },
                    { type = "characteristic", name = "Fel", cost = 100, amount = 5 },
                    { type = "characteristic", name = "S",   cost = 100, amount = 5 },
                    { type = "characteristic", name = "T",   cost = 250, amount = 5 },
                    { type = "skill",          name = "Command",    cost = 100 },
                    { type = "skill",          name = "Intimidate", cost = 100 },
                    { type = "talent",         name = "Frenzy",     cost = 200 },
                    { type = "talent",         name = "Flagellant", cost = 200 },
                },
            },
            {
                rankNumber = 2,
                rankTitle = "Crusader",
                xpThreshold = 500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "WP",  cost = 250, amount = 5 },
                    { type = "characteristic", name = "S",   cost = 250, amount = 5 },
                    { type = "characteristic", name = "Fel", cost = 250, amount = 5 },
                    { type = "skill",          name = "Scholastic Lore (Imperial Creed)", cost = 200 },
                    { type = "skill",          name = "Medicae",   cost = 200 },
                    { type = "talent",         name = "Battle Rage", cost = 300 },
                    { type = "talent",         name = "True Grit",   cost = 300 },
                },
            },
            {
                rankNumber = 3,
                rankTitle = "Arch-Cardinal",
                xpThreshold = 1500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "WP",  cost = 500, amount = 5 },
                    { type = "characteristic", name = "Fel", cost = 500, amount = 5 },
                    { type = "skill",          name = "Command",  cost = 300 },
                    { type = "skill",          name = "Charm",    cost = 300 },
                    { type = "talent",         name = "Iron Will",           cost = 500 },
                    { type = "talent",         name = "Touched by the Fates", cost = 500 },
                },
            },
        },
    },
    {
        name = "Seneschal",
        description = "The eyes, ears, and coin-purse of the Rogue Trader dynasty. You deal in information, leverage, and discreet transactions. Where others use blades, you use words and well-placed bribes.",
        hp = 34.0,
        defense = 1.0,
        power = 3.0,
        invSize = 30,
        startingEquipment = { "Laspistol", "Combat Knife", "Flak Armor" },
        ranks = {
            {
                rankNumber = 1,
                rankTitle = "Seneschal",
                xpThreshold = 0,
                startingSkills = { "Commerce", "Deceive" },
                startingTalents = { "Pistol Weapon Training (Universal)" },
                advances = {
                    { type = "characteristic", name = "Fel", cost = 100, amount = 5 },
                    { type = "characteristic", name = "Int", cost = 100, amount = 5 },
                    { type = "characteristic", name = "Per", cost = 100, amount = 5 },
                    { type = "characteristic", name = "Ag",  cost = 250, amount = 5 },
                    { type = "skill",          name = "Commerce",  cost = 100 },
                    { type = "skill",          name = "Deceive",   cost = 100 },
                    { type = "skill",          name = "Evaluate",  cost = 100 },
                    { type = "talent",         name = "Peer (Underworld)", cost = 200 },
                    { type = "talent",         name = "Cover-Up",          cost = 200 },
                },
            },
            {
                rankNumber = 2,
                rankTitle = "Master of Whispers",
                xpThreshold = 500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "Fel", cost = 250, amount = 5 },
                    { type = "characteristic", name = "Int", cost = 250, amount = 5 },
                    { type = "characteristic", name = "Per", cost = 250, amount = 5 },
                    { type = "skill",          name = "Inquiry",  cost = 200 },
                    { type = "skill",          name = "Barter",   cost = 200 },
                    { type = "talent",         name = "Step Aside",    cost = 300 },
                    { type = "talent",         name = "Unremarkable",  cost = 300 },
                },
            },
            {
                rankNumber = 3,
                rankTitle = "Grand Seneschal",
                xpThreshold = 1500,
                startingSkills = {},
                startingTalents = {},
                advances = {
                    { type = "characteristic", name = "Fel", cost = 500, amount = 5 },
                    { type = "characteristic", name = "Int", cost = 500, amount = 5 },
                    { type = "skill",          name = "Charm",    cost = 300 },
                    { type = "skill",          name = "Blather",  cost = 300 },
                    { type = "talent",         name = "Master of All Trades", cost = 500 },
                    { type = "talent",         name = "Infused Knowledge",    cost = 500 },
                },
            },
        },
    },
}
